arch: s390x
language: clojure

lein: lein
dist: bionic

# before_install:
#   - wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
#   - echo "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ bionic main" | sudo tee /etc/apt/sources.list.d/adoptopenjdk.list
#   - sudo apt update
  
before_script:
  # Give MongoDB server some time to boot
  - wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
  - echo "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ bionic main" | sudo tee /etc/apt/sources.list.d/adoptopenjdk.list
  - sudo apt update
  - sleep 15
  - mongod --version
  - ./bin/ci/before_script.sh
script: lein do clean, javac, test
jdk: openjdk10
services:
  - mongodb
branches:
  only:
    - master
    - 3.5.x-stable
